package com.example.demo.error;

public enum ErrorCode {
    // Custom error codes
    DUPLICATE_VALUE,
    REFERENTIAL_INTEGRITY_VIOLATION,
    DATA_INTEGRITY_VIOLATION,
    RESOURCE_NOT_FOUND,
    VALIDATION_FAILED,
    UNKNOWN_JSON_FIELD,
    INVALID_ENUM_VALUE,
    INVALID_FIELD_VALUE,
    TYPE_MISMATCH,
    INTEGER_OVERFLOW,
    MALFORMED_JSON,

    // Internal error codes
    MALFORMED_REQUEST_BODY,
    METHOD_NOT_ALLOWED,
    UNSUPPORTED_MEDIA_TYPE,
    NOT_ACCEPTABLE,
    MISSING_PATH_VARIABLE,
    MISSING_REQUEST_PARAMETER,
    MISSING_REQUEST_PART,
    REQUEST_BINDING_ERROR,
    ROUTE_NOT_FOUND,
    REQUEST_TIMEOUT,
    PAYLOAD_TOO_LARGE,
    CONVERSION_NOT_SUPPORTED,
    PARAMETER_TYPE_MISMATCH,
    MESSAGE_NOT_WRITABLE,
    METHOD_VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR
}
