spring.application.name=demo
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.jpa.hibernate.ddl-auto=create-drop
spring.jackson.deserialization.fail-on-unknown-properties=true
management.tracing.sampling.probability=1.0
